eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      host: localhost
      port: 27071
      database: orderdb
      repositories:
        enabled: true

